var a = prompt("select first number");
var b = prompt("select secound number");
a = parseInt(a);
b = parseInt(b);
var result1 = a + b;
var result2 = a * b;
var result3 = a - b;
var result4 = a / b;
console.log(result1);
console.log(result2);
console.log(result3);
console.log(result4);
